### ISSUE TITLE
UE4.26 生成ue.d.ts后World中没有SpawnActor了

### ISSUE THREAD

**Issue by greatzane** [chexiongsheng/puerts_unreal_demo#15]
我看了一下UWorld中确实SpawnActor不是UFUNCTION，请问官方用的UE4版本是哪个？4.26有什么替代方案？

**Comment by chexiongsheng** [comment]
所有版本都没有，都需要自己写扩展函数支持：https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/Source/puerts_unreal_demo/WorldExtensionMethods.cpp
