### ISSUE TITLE
Engine.h内的USTRUCT,无法自动解析出来

### ISSUE THREAD

**Issue by zhmxiaowo** [chexiongsheng/puerts_unreal_demo#21]
![image](https://user-images.githubusercontent.com/16378793/130382268-ce35d9af-eafa-4cbb-93d7-b4fc36447c49.png)
FNetDriverDefinition可以正常使用
FNamedNetDriver没有提示,应该是自动绑定没有成功

**Comment by Streliteela** [comment]
请问这个有解决么？我在cpp里面定义了结构体ts也是没有识别出来

**Comment by chexiongsheng** [comment]
> 请问这个有解决么？我在cpp里面定义了结构体ts也是没有识别出来

看faq，默认引用了的ustruct才会生成
