### ISSUE TITLE
win7 vs2017 编译demo报错

### ISSUE THREAD

**Issue by stdnxd** [chexiongsheng/puerts_unreal_demo#24]
UE引擎版本 4.26.2
win7系统 vs2017
更新到最新版本 编译报错

1>S:/Code/macmini/Game/UE4/puerts/puerts_unreal_demo_check/Plugins/Puerts/Source/JsEnv/Private/PesapiAddonLoad.cpp(107): error C2894: 模板不能声明为有“C”链接
1>S:/Code/macmini/Game/UE4/puerts/puerts_unreal_demo_check/Plugins/Puerts/Source/JsEnv/Private/PesapiAddonLoad.cpp(111): error C2894: 模板不能声明为有“C”链接

**Comment by chexiongsheng** [comment]
应该到这里提：https://github.com/Tencent/puerts
