### ISSUE TITLE
13号的版本vs2019编译不过

### ISSUE THREAD

**Issue by terst6** [chexiongsheng/puerts_unreal_demo#25]
12号的可以，那个jsclass register.好对v8引用有几个错误

**Comment by chexiongsheng** [comment]
完整信息呢？是哪个文件引用v8config.h？

**Comment by chexiongsheng** [comment]
看上去是你的编译环境缺少一些宏导致的，比如_MSC_VER，这个应该在vs环境，或者cl编译都会自动定义，不知道为啥你那没有。

**Comment by terst6** [comment]
其它版本都没有问题
13号的版本比12号的版本只修改了一个类Plugins\Puerts\Source\DeclarationGenerator\Public\TypeScriptDeclarationGenerator.h
在里面增加了一个头文件引用：
#include "JSClassRegister.h"
是这个文件导致了编译错误，它对你说的宏定义有两个，__clang__ 和另外一个、我的都是灰色的，没有命中宏定义，如果强制在项目添加会有其它更多错误出来
