### ISSUE TITLE
蓝图中Interface变量导出问题

### ISSUE THREAD

**Issue by ivanzhang85** [chexiongsheng/puerts_unreal_demo#36]
蓝图中配置了 interface类型的变量, 但是自动导出的时候, 变量类型的引用出错了

![%2~ 9S}889D7KV}$ 2@VTTS](https://user-images.githubusercontent.com/800061/232694948-6b17c5a0-66e5-463a-9c22-77721319891f.jpg)
![4I07XG(6_ZOW{EL W{~4J$X](https://user-images.githubusercontent.com/800061/232694966-cd928441-110e-4a92-9af7-dcdd6c4cbbc8.jpg)
![9G0) J7UYHHXEIYTB$2Z@`2](https://user-images.githubusercontent.com/800061/232694981-b8bd217c-ddae-452a-869a-888f960aadf6.jpg)

**Comment by chexiongsheng** [comment]
https://github.com/Tencent/puerts/commit/eaf637a7c083893fcdc565c0a2ade1ab364fd0ed
