### ISSUE TITLE
QuickStart.ts中的world.SpawnActor可能使用得不太规范

### ISSUE THREAD

**Issue by xRosemary** [chexiongsheng/puerts_unreal_demo#37]
QuickStart.ts中使用world.SpawnActor时，Level可能还未被加载，此时生成一个Actor可能会在Level成功加载后被清除。

**Comment by chexiongsheng** [comment]
确实那个脚本不是哪里都能正常跑。
那脚本主要是希望尽可能简单的跑起来，演示足够的常用特性
