### ISSUE TITLE
unreal 5.2内存泄漏

### ISSUE THREAD

**Issue by cloudending** [chexiongsheng/puerts_unreal_demo#40]
![16871392364485](https://github.com/chexiongsheng/puerts_unreal_demo/assets/5187578/efa9c3a3-590f-445c-9d55-8454c426dcf9)
unreal 5.2版本打开工程后，直接运行TsGameInstance，跑通后无异常并停止运行，工程打开后内存会不断增长，最后出现out of memory错误。
另外unreal 4.27.2版本不会出现这种问题。

**Comment by chexiongsheng** [comment]
我在5.2.1试了没这问题。
按理关闭了JsEnv就没开销了。会不会是UE5.2的bug？ue编辑器经常有些后台任务，curl去联网什么的，是不是这些后台任务内存泄露了？

**Comment by xiasun** [comment]
> 我在5.2.1试了没这问题。 按理关闭了JsEnv就没开销了。会不会是UE5.2的bug？ue编辑器经常有些后台任务，curl去联网什么的，是不是这些后台任务内存泄露了？

5.1.1也发现了类似的问题，
Play之前进程占用内存1.9G，Play时2.3G，Play结束2.3G，过了10分钟到2.7G了，大约1秒2M上升
但是偶尔内存占用会下降一下

4.27和5.0.3看起来正常
