### ISSUE TITLE
示例项目编译失败

### ISSUE THREAD

**Issue by solairewrite** [chexiongsheng/puerts_unreal_demo#45]
![image](https://github.com/chexiongsheng/puerts_unreal_demo/assets/36910977/bb00f829-eab6-4989-ac5b-3aa6a07c956e)

**Comment by solairewrite** [comment]
UE5.3源码版

**Comment by chexiongsheng** [comment]
好像ue5.3下继承UWidget就会这样，我起一个空项目，搞个类继承UWidget也会报错。

你可以把demo里继承UWidget的地方都去掉（删了Plugins\ReactUMG）

**Comment by solairewrite** [comment]
试过了,依旧编译不过,还是一样的报错

**Comment by chexiongsheng** [comment]
都删了相关代码怎么还是一样的错误？你IDE的编译缓存吧

**Comment by solairewrite** [comment]
不是缓存的问题,删了Plugins\ReactUMG还是相同的报错,应该是项目中或者插件中还有Widget,但是报错信息看不出来哪里有

**Comment by solairewrite** [comment]
能不能加个UE5.3实测能运行的分支

**Comment by chexiongsheng** [comment]
你更新下，同时也删除Plugins\ReactUMG就可以编译通过了

**Comment by solairewrite** [comment]
可以编过了,不过游戏运行的瞬间崩溃
