### ISSUE TITLE
UE5.3 源码版,游戏运行瞬间崩溃

### ISSUE THREAD

**Issue by solairewrite** [chexiongsheng/puerts_unreal_demo#46]
![image](https://github.com/chexiongsheng/puerts_unreal_demo/assets/36910977/c326a277-5153-4bbc-8808-5eb03f2e4269)

**Comment by solairewrite** [comment]
![image](https://github.com/chexiongsheng/puerts_unreal_demo/assets/36910977/899354b9-3a0b-4ffa-bb99-5b453d936689)

**Comment by chexiongsheng** [comment]
下载错v8版本了，要用最新的：https://github.com/puerts/backend-v8/releases/tag/V8_9.4.146.24_230822
