### ISSUE TITLE
How to use puerts with ue4 game ability system ?

### ISSUE THREAD

**Issue by Kiddinglife** [chexiongsheng/puerts_unreal_demo#7]
Hey, I am wondering how easy/hard to bind GAS interfaces via puerts ? 
https://docs.unrealengine.com/en-US/InteractiveExperiences/GameplayAbilitySystem/GameplayAbility/index.html
Thanks.

**Comment by chexiongsheng** [comment]
All class with UCLASS macro, all function with UFUNCTION macro all property with  UPROPERTY can be access in typescript. 
API without those macros you can wraper like [this](https://github.com/chexiongsheng/puerts_unreal_demo/blob/master/Plugins/Puerts/Source/Puerts/Private/ObjectExtension.h).
Enable GAS and re-generate the ue.d.ts than you can use the api of GAS by press the "ue.d.ts" toolbar button.
