### ISSUE TITLE
tsx文件的更改无法被PurtesEditor更新

### ISSUE THREAD

**Issue by huangwc94** [chexiongsheng/puerts_unreal_demo#9]
尝试使用内置的react-umg开发UI，发现每次更改`.tsx`文件后，editor并不能自动更新，即使手动跑了`tsc`命令也无济于事，目前只发现两种办法可以刷新更新后的tsx文件
1. 文件重新命名，重新使用tsc生成（手动移除content/javascript下的js文件也不行，只能重命名）
2. 重启UEEditor

以下是我的操作步骤：
1. clone到本地
2. 在如下地方跑了npm install:
    根目录
    Content/Javascript
    Content/Javascript/PuertsEditor
3. 打开uproject之后开启了PuertsEditor Module Enabled，没有开其他debug的东西
本地环境：
1. windows 10
2. node 12.18.2
3. npm 6.14.5
4. Unreal 26.1

此外，有没有办法可以手动根据ts生成蓝图，我觉得这个目录结构太混乱了，到处都是javascript和typescript相关的文件夹，有没有办法可以把所有JS相关的文件统一到一起？（我pull官方plugin也给我放一堆文件夹）

**Comment by chexiongsheng** [comment]
现在停止播放会重置js虚拟机，你更新试试

**Comment by huangwc94** [comment]
嗯，看到了commit，问一下，有没有办法可以再开始播放PIE之前重置一遍？

**Comment by huangwc94** [comment]
当然停止播放也很有用，如果我有一些SetTimeinterval没有手动关掉的话，结束PIE之后貌似还在tick。而且event emitter会多次绑定。这样解决了一堆麻烦，多谢！

**Comment by chexiongsheng** [comment]
> 嗯，看到了commit，问一下，有没有办法可以再开始播放PIE之前重置一遍？

有PreBeginPIE，BeginPIE，PostPIEStarted这些事件，你选一个照着加下就可以了
